### ISSUE TITLE
Could you upload your models somewhere else instead of OneDrive?

### ISSUE THREAD

**Issue by americanexplorer13** [e4s2023/E4S2023#4]
Thank you for your paperwork, it sounds really cool, but unfortunately it's impossible for me to download your models from OneDrive due to constant corruption of zip-files. Could you please upload them somewhere else?

**Comment by ygtxr1997** [comment]
It seems I mistaken the authority management of the [OneDrive shared link](https://mail2sysueducn-my.sharepoint.com/personal/yuang7_mail2_sysu_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyuang7%5Fmail2%5Fsysu%5Fedu%5Fcn%2FDocuments%2Fshared%2FE4S2023&ga=1). Now I have updated the link, making it only accessable but not editable for the users. Can you try it again? If it still doesn't work, let me know. I would upload the pretrained weights to [Google Drive](https://drive.google.com/) or [Baidu Cloud Drive](https://pan.baidu.com/disk/main), which one is more suitable?

**Comment by ygtxr1997** [comment]
I've uploaded the weights to [Google Drive](https://drive.google.com/drive/folders/1xq3cN-p1ubLZQaVVF0qzH4j_-MukKGvv?usp=sharing).
