### ISSUE TITLE
 Time-consuming Problem

### ISSUE THREAD

**Issue by YYY7C** [e4s2023/E4S2023#7]
The results of this method are amazing. But it takes almost two hours to process a 3 second 1080p video on the 4090, is it normal for the video to take a long time to process?

`
tuning e4s_g 79/80: 100%█████████████████████████████| 74/74 [01:08<00:00,  1.08it/s]
100%|████████████████████████████████████| 80/80 [1:29:25<00:00, 67.07s/it]

Finished fine-tuning e4s generator!
`

**Comment by aqunyawa** [comment]
I guess it just don't utilize your GPU power at all. Can you provide screenshots of your GPU and VRAM load while processing a swap?

**Comment by ygtxr1997** [comment]
It could be possible. Since we use [STIT](https://github.com/rotemtzaban/STIT/tree/main) to tune the model for stablizing the video frames, this tuning step requires training on all the video frames for default 80 epochs. It's quite time-consuming.

**Comment by ygtxr1997** [comment]
It could be time-consuming because we use [STIT](https://github.com/rotemtzaban/STIT/tree/main) to finetune the model for all the video frames with default 80 epochs. Despite this, we suggest you to make sure your code is running on GPU by checking the GPU rate and VRAM.

**Comment by YYY7C** [comment]
Thanks for the answer, I'll check out the resource usage.
